name: bsd

env:
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - ".github/workflows/ci_bsd.yml"
      - "!concepts/**"


jobs:
  test:
    runs-on: ubuntu-22.04

    name: FreeBSD

    env:
      FC: gfortran
      CC: gcc
      CXX: g++

    steps:

    - uses: actions/checkout@v4

    - name: Test in FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'CC CXX FC'

        prepare: pkg install -y cmake gcc13

        run: cmake --workflow --preset default
